name: rsdb
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.9
  - numpy=1.24.3
  - matplotlib
  - pip
  - pip:
      - ipython
      - pandas
      - imageio
      - moviepy
      - absl-py==1.4.0
      - nltk==3.8.1
      - scipy==1.10.1
      - black
      - plotly
      - scikit-learn
      - tensorflow=2.13.0
      - tensorflow-recommenders=0.7.3
      - keras-tuner=1.4.7
      - tqdm
      - pathlib
      - pandas

