name: rsdb
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.9
  - numpy
  - matplotlib
  - pip
  - pip:
      - ipython
      - pandas
      - imageio
      - moviepy
      - peft==0.3.0
      - datasets==2.12.0
      - fire==0.5.0
      - evaluate==0.4.0
      - absl-py==1.4.0
      - nltk==3.8.1
      - rouge_score==0.1.2
      - bitsandbytes==0.39.0
      - scipy==1.10.1
      - black
      - plotly
      - scikit-learn
      - tensorflow
      - kerastuner
      - tqdm
      - pathlib
      - pandas

