tuning:
  train_frac: 0.8
  random_state: 42
  shuffle_buffer_size: 1024
  batch_size: 4096
  search_epochs: 20
  max_epochs: 100
  factor: 3
  directories:
    tdlf: "hypertune_tdlf"
    fpmc: "hypertune_fpmc"
  project_names:
    tdlf: "tdlf_tuning"
    fpmc: "fpmc_tuning"

tdlf_hyperparameters:
  l2_reg:
    min: 1e-4
    max: 1e-3
    sampling: "log"
  dense_units:
    min: 64
    max: 128
    step: 32
  embedding_dim:
    min: 30
    max: 90
    step: 30
  time_bins:
    min: 10
    max: 30
    step: 10
  learning_rate:
    min: 1e-4
    max: 1e-3
    sampling: "log"
  decay_rate: 0.5
  decay_steps: 1000

fpmc_hyperparameters:
  l2_reg:
    min: 1e-5
    max: 1e-2
    sampling: "log"
  embedding_dim:
    min: 90
    max: 128
    step: 8
  learning_rate:
    min: 1e-4
    max: 1e-2
    sampling: "log"
